const productData = [
    { id: 1, category: 'Endodontics', name: 'Eugenol Liquid JK', price: '100 EGP', desc: 'Usage: Mixed with zinc oxide powder to form zinc oxide-eugenol (ZOE) cement for temporary fillings, cavity linings, and root canal sealers; also provides local anesthetic and antiseptic effects for sedating dental pulp | Quantity/Size: 1 Bottle × 15 ml  | Origin: JK Dental Vision — Egypt ', img: 'assets/products/endodontics/endo_prod_1.webp' },
    { id: 2, category: 'Endodontics', name: 'Well-Root PT', price: '600 EGP', desc: 'Usage: Pulp capping, repair of root perforation, root-end filling (retrograde filling), apexification, and repair of internal/external root resorption | Quantity/Size: 1 cap × 0.25 g each (Premixed putty paste in single-dose capsules) | Origin: Vericom Co., Ltd. — South Korea', img: 'assets/products/endodontics/endo_prod_2.webp' },
    { id: 3, category: 'Endodontics', name: 'Metapex Plus', price: '575 EGP', desc: 'Usage: Temporary root canal filling material, intracanal medicament for infected root canals, apexification, hard tissue formation, and root resorption treatment | Quantity/Size: 1 Syringe × 2.2 g + disposable tips | Origin: Meta Biomed Co., Ltd. — South Korea', img: 'assets/products/endodontics/endo_prod_3.webp' },
    { id: 4, category: 'Endodontics', name: 'Metapaste Plus', price: '575 EGP', desc: 'Usage: Temporary root canal filling material, water-soluble intracanal medicament for root canal disinfection, apexification, and temporary exudate control | Quantity/Size: 1 Syringe × 2.2 g + disposable tips | Origin: Meta Biomed Co., Ltd. — South Korea', img: 'assets/products/endodontics/endo_prod_4.webp' },
    { id: 5, category: 'Endodontics', name: 'NOP long Dental Needles (Spident)', price: '265 EGP', desc: 'Usage: Administering local anesthetic injections during dental procedures | Quantity/Size: 1 Box × 100 Needles (27G Long / 0.4 × 38 mm) | Origin: Spident Co., Ltd. — South Korea', img: 'assets/products/endodontics/endo_prod_5.webp' },
    { id: 6, category: 'Endodontics', name: 'NOP Short Dental Needles (Spident)', price: '265 EGP', desc: 'Usage: Administering local anesthetic injections during dental procedures (infiltration or nerve block anesthesia) | Quantity/Size: 1 Box × 100 Needles (30G Short / 0.3 × 21 mm) | Origin: Spident Co., Ltd. — South Korea', img: 'assets/products/endodontics/endo_prod_6.webp' },
    { id: 7, category: 'Endodontics', name: 'ENDO-TOP Disposable Irrigation Needles', price: '350 EGP', desc: 'Usage: Root canal and periodontal pocket irrigation, flushing canals with antiseptic solutions  | Quantity/Size: 1 Box × 100 Pieces (Bendable, end-closed / side-vented needles | Origin: Cerkomed Medical Company — Poland', img: 'assets/products/endodontics/endo_prod_7.webp' },
    { id: 8, category: 'Endodontics', name: 'Dental Teflon Tape', price: '15 EGP', desc: 'Usage: Isolating adjacent teeth during etching/bonding/composite procedures, protecting screw access holes in dental implant abutments, and providing temporary gingival retraction | Quantity/Size: 1 Roll | Origin: Egypt', img: 'assets/products/endodontics/endo_prod_8.webp' },
    { id: 9, category: 'Endodontics', name: 'MD-ChelCream EDTA Cream', price: '475 EGP for 1 syr', desc: 'Usage: Root canal chelating agent and lubricant used during chemo-mechanical preparation, helping to soften canal walls, remove inorganic smear layers, and facilitate endodontic instrument navigation | Quantity/Size: 2 Syringes × 5.4 ml (7 g) each + disposable tips | Origin: Meta Biomed Co., Ltd. — South Korea', img: 'assets/products/endodontics/endo_prod_9.webp' },
    { id: 10, category: 'Endodontics', name: 'Endo Ruler (Aluminum)', price: '40 EGP', desc: 'Usage: Measuring working length of root canal instruments (files, reamers, gutta-percha points) during endodontic treatment | Quantity/Size: 1 Piece (Autoclavable aluminum ruler, scale range 0–35 mm / 0–40 mm) | Origin: China', img: 'assets/products/endodontics/endo_prod_10.webp' },
    { id: 11, category: 'Endodontics', name: 'Endo Ruler (Rotex)', price: '35 EGP', desc: 'Usage: Measuring working length of endodontic instruments (files, reamers, gutta-percha points) during root canal treatment | Quantity/Size: 1 Piece / Pack Autoclavable | Origin: Rotex Dental Supplies — China', img: 'assets/products/endodontics/endo_prod_11.webp' },
    { id: 12, category: 'Endodontics', name: 'Sanctuary Dental Dam Latex (Blue)', price: '375 EGP', desc: 'Usage: Isolation of the treatment area during endodontic and dental procedures to maintain a dry, clean, and aseptic operating field | Quantity/Size: 6" x 6" size sheets. 36 sheets | Origin & Manufacturer: Sanctuary Health (Sanctuary Dental Dam)', img: 'assets/products/endodontics/endo_prod_12.webp' },
    { id: 13, category: 'Endodontics', name: 'Dental Dam Sheets (Pure)', price: '325 EGP', desc: 'Usage: Isolating the operating field during endodontic and restorative dental procedures to maintain a moisture-free environment | Quantity/Size: 1 Box × 36 Sheets (6" × 6" / Medium /heavy latex sheets) | Origin: Pure Latex Products — Malaysia / China', img: 'assets/products/endodontics/endo_prod_13.webp' },
    { id: 14, category: 'Endodontics', name: 'Rubber Dam Clamps (Stainless Steel)', price: '45 EGP for a 1 pcs', desc: 'Usage: Anchoring and securing rubber dam sheets to anchor teeth for operative field isolation during endodontic and restorative procedures | Quantity/Size Clamps all sizes for molars, premolars, anterior teeth, and cervical cavities | Origin: Pakistan', img: 'assets/products/endodontics/endo_prod_14.webp' },
    { id: 15, category: 'Endodontics', name: 'Dental Rubber Dam Frame', price: '55 EGP', desc: 'Usage: Holding and maintaining tension on rubber dam sheets to secure clear isolation around the working field during endodontic and operative dental procedures | Quantity/Size: 1 Piece | Origin: Pakistan ', img: 'assets/products/endodontics/endo_prod_15.webp' },
    { id: 16, category: 'Endodontics', name: 'Foldable Dental Rubber Dam Frame Plastic', price: '100 EGP', desc: 'Usage: Holding and stretching rubber dam sheets during dental procedures, featuring a hinged design that folds in half to facilitate intraoperative X-rays without removing the frame or dam | Quantity/Size: 1 autoclavable plastic | Origin: China', img: 'assets/products/endodontics/endo_prod_16.webp' },
    { id: 17, category: 'Endodontics', name: 'ADSEAL Plus', price: '910 EGP', desc: 'Usage: Permanent obturation of root canals in combination with gutta-percha points, offering high radiopacity, bio-compatibility, and reliable hermetic sealing | Quantity/Size: 1 Dual Syringe × 13.5 g | Origin: Meta Biomed Co., Ltd. — South Korea', img: 'assets/products/endodontics/endo_prod_17.webp' },
    { id: 18, category: 'Endodontics', name: 'Carvene Gutta Percha Solvent', price: '350 EGP', desc: 'Usage: Softening and dissolving gutta-percha points during endodontic retreatment to remove old root canal filling materials; also used for cleaning endodontic instruments | Quantity/Size: 1 Bottle × 10 ml | Origin: Prevest DenPro Limited — India', img: 'assets/products/endodontics/endo_prod_18.webp' },
    { id: 19, category: 'Endodontics', name: 'Sodium Hypochlorite 5% JK', price: '45 EGP', desc: 'Usage: Primary irrigating solution for root canal disinfection during endodontic treatment, effective for dissolving organic necrotic tissue, killing bacteria, and flushing debris | Quantity/Size: 1 Bottle × 500 ml | Origin: JK Dental Vision — Egypt', img: 'assets/products/endodontics/endo_prod_19.webp' },
    { id: 20, category: 'Endodontics', name: 'E-FLEX BLUE Rotary Files (Eighteeth)', price: '325 EGP', desc: 'Usage: Root canal cleaning and shaping during endodontic treatment | Quantity/Size: 1 Pack × 6 Files (Assorted sizes: #17/08 19mm, #20/04 25mm, #20/04 25mm, #25/04 25mm, #25/04 25mm, #30/04 25mm) | Origin: (Eighteeth) — China', img: 'assets/products/endodontics/endo_prod_20.webp' },
    { id: 21, category: 'Endodontics', name: 'E-FLEX GOLD Rotary Files (Eighteeth)', price: '325 EGP', desc: 'Usage: Root canal cleaning, shaping, and canal preparation in endodontic procedures | Quantity/Size: 1 Pack × 6 Files (Assorted sizes: #17/08 19mm, #15/03 25mm, #20/04 25mm, #25/04 25mm, #30/04 25mm, #35/04 25mm) | Origin: (Eighteeth) — China', img: 'assets/products/endodontics/endo_prod_21.webp' },
    { id: 22, category: 'Endodontics', name: 'M-Pro NiTi Rotary Files Assorted', price: '275 EGP', desc: 'Usage: Root canal mechanical preparation, cleaning, and shaping during endodontic | Quantity/Size: 1 Pack × 6 Files (Assorted sequence, 25 mm length; typically includes sizes #18/09, #20/04, #25/06, or similar sequence) | Origin: IMD Medical / Alex Dent — China', img: 'assets/products/endodontics/endo_prod_22.webp' },
    { id: 23, category: 'Endodontics', name: 'M-Pro Gold Rotary Files Assorted', price: '325 EGP', desc: 'Usage: Root canal cleaning, shaping, and mechanical canal preparation in endodontic procedures | Quantity/Size: 1 Pack × 6 Files (Assorted sequence, 25 mm length: #17/08, #12/02 or #16/02 glide path, #20/04, #25/06, #30/04, #35/04) | Origin: China', img: 'assets/products/endodontics/endo_prod_23.webp' },
    { id: 24, category: 'Endodontics', name: 'M-Pro Gold  Rotary Files Single Size 0.4/ 0.6', price: '325 EGP', desc: 'Usage: Root canal cleaning, shaping, and apical enlargement during endodontic treatment | Quantity/Size: 1 Pack × 6 Files (Refill pack of identical single size, 25 mm length; available in individual sizes such as #20/04/06, #25/04/06, or #30/04/06) | Origin: China', img: 'assets/products/endodontics/endo_prod_24.webp' },
    { id: 25, category: 'Endodontics', name: 'Rogin Dental Rotary Files', price: '350 EGP', desc: 'Usage: Root canal cleaning, shaping, and biomechanical preparation during endodontic treatment | Quantity/Size: 1 Blister Pack × 6 Files (Assorted sequence or single sizes, 21 mm / 25 mm / 31 mm lengths) | Origin: China', img: 'assets/products/endodontics/endo_prod_25.webp' },
    { id: 26, category: 'Endodontics', name: 'M-Pro NiTi Rotary Files Assorted 31mm', price: '395 EGP', desc: 'Usage: Mechanical cleaning, shaping, and preparation of extra-long root canals during endodontic treatment | Quantity/Size: 1 Pack × 6 Files (Assorted sequence, 31 mm length: #18/.04, #20/.04, #25/.06) | Origin: China', img: 'assets/products/endodontics/endo_prod_26.webp' },
    { id: 27, category: 'Endodontics', name: 'SOCO SC Rotary Files Assorted', price: '325 EGP', desc: 'Usage: Root canal cleaning, shaping, and biomechanical preparation during endodontic treatment | Quantity/Size: 1 Pack × 6 Files (Assorted sequence, 21 mm / 25 mm lengths; typical sequence includes orifice opener, glide path, and shaping files) | Origin: SOCO. — China', img: 'assets/products/endodontics/endo_prod_27.webp' },
    { id: 28, category: 'Endodontics', name: 'NiTi Retreatment Files (Rogin Dental)', price: '395 EGP', desc: 'Usage: Removing filling materials (such as gutta-percha and root canal sealers) from root canals during endodontic retreatment procedures | Quantity/Size: 1 Pack × 6 Files (Assorted sequence: D1 #30/09 16mm, D2 #25/08 18mm, D3 #20/07 22mm) | Origin:  Rogin Medical — China', img: 'assets/products/endodontics/endo_prod_28.webp' },
    { id: 29, category: 'Endodontics', name: 'Endo Ice Spray (Maquira)', price: '875 EGP', desc: 'Usage: Thermal pulp vitality testing to evaluate endodontic health and nerve response by applying a cold stimulus (-50°C) to teeth using a cotton pellet | Quantity/Size: 1 Spray Can × 200 ml  | Origin: Maquira Dental Products — Brazil', img: 'assets/products/endodontics/endo_prod_29.webp' },
    { id: 30, category: 'Endodontics', name: 'Formocresol Solution JK', price: '100 EGP', desc: 'Usage: Vital pulpotomy medicament and root canal disinfectant used for dental pulp mummification and devitalization, primarily in primary teeth endodontic therapy | Quantity/Size: 1 Dropper Bottle × 15 ml | Origin: JK Dental Vision — Egypt', img: 'assets/products/endodontics/endo_prod_30.webp' },
    { id: 31, category: 'Endodontics', name: 'CeraSeal Root Canal Sealer', price: '2300 EGP', desc: 'Usage: Permanent root canal obturation providing excellent biocompatibility, zero shrinkage, high radiopacity, and antibacterial chemical sealing via calcium silicate composition | Quantity/Size: 1 Pre-filled Syringe × 2 g + intra-canal tips | Origin: Meta Biomed Co., Ltd. — South Korea', img: 'assets/products/endodontics/endo_prod_31.webp' },
    { id: 32, category: 'Endodontics', name: 'Dia-Root Bio Sealer (DiaDent)', price: '2100 EGP', desc: 'Usage: Permanent root canal filling and sealing, featuring a premixed bioceramic calcium silicate paste that offers biocompatibility, zero shrinkage, high radiopacity, and tissue healing support | Quantity/Size: 1 Pre-filled Syringe × 2 g + intra-canal tips | Origin: DiaDent Group International — South Korea', img: 'assets/products/endodontics/endo_prod_32.webp' },
    { id: 33, category: 'Endodontics', name: 'Rubber Dam Clamp Forceps', price: '300 EGP', desc: 'Usage: Spreading and positioning rubber dam clamps over the anchor teeth to secure and stabilize rubber dam sheets during isolation in endodontic and restorative dental procedures | Quantity/Size: 1 | Origin: Pakistan', img: 'assets/products/endodontics/endo_prod_33.webp' },
    { id: 34, category: 'Endodontics', name: 'Rubber Dam Hole Punch', price: '425 EGP', desc: 'Usage: Punching clean, precise holes of varying sizes into rubber dam sheets to accommodate teeth for operative isolation during endodontic and restorative dental procedures | Quantity/Size: 1 Piece | Origin: Pakistan', img: 'assets/products/endodontics/endo_prod_34.webp' },
    { id: 35, category: 'Endodontics', name: 'Needle Holder', price: '45 EGP', desc: 'Usage: Holding and guiding surgical needles | Quantity/Size: 1 Piece 14 cm  or 16 cm | Origin: Pakistan', img: 'assets/products/endodontics/endo_prod_35.webp' },
    { id: 36, category: 'Endodontics', name: 'Needle Holder (18 cm)', price: '110 EGP', desc: 'Usage: Securely holding and driving surgical needles | Quantity/Size: 1 Piece, 18 cm | Origin: Pakistan', img: 'assets/products/endodontics/endo_prod_36.webp' },
    { id: 37, category: 'Endodontics', name: 'SDF - Silver Diamine Fluoride 38%', price: '450 EGP', desc: 'Usage: Non-invasive caries arresting agent and dentin desensitizer used to halt dental caries progression and relieve hypersensitivity without requiring anesthesia or drilling | Quantity/Size: 1 Dropper Bottle × 5 ml | Origin: Eta Dent — Egypt', img: 'assets/products/endodontics/endo_prod_37.webp' },
    { id: 38, category: 'Endodontics', name: 'Endoseal MTA Root Canal Sealer', price: '2850 EGP', desc: 'Usage: Permanent root canal obturation and filling, providing excellent biocompatibility, hermetic sealing, mineralization promotion, and antibacterial properties via a paste-type MTA (Mineral Trioxide Aggregate) formula | Quantity/Size: 1 Pre-filled Syringe × 3 g | Origin: South Korea', img: 'assets/products/endodontics/endo_prod_38.webp' },
    { id: 39, category: 'Endodontics', name: 'MTA+ Mini Root Canal Repair Material', price: '425 EGP', desc: 'Usage: Root canal perforation repair, internal/external resorption treatment, apexification, direct pulp capping, and retrograde root end filling in surgical endodontics | Quantity/Size: 1 Bottle × 1 ml MTA | Origin: Poland', img: 'assets/products/endodontics/endo_prod_39.webp' },
    { id: 40, category: 'Endodontics', name: 'MTA Root Canal Material JK', price: '150 EGP', desc: 'Usage: Root perforation repair, pulp capping, pulpotomy, apexification, and retrograde filling in endodontic treatments using Mineral Trioxide Aggregate (MTA) | Quantity/Size: 1 Kit (2 Powder Vials + 2 Liquid Dropper Bottles) | Origin: JK Dental Vision — Egypt', img: 'assets/products/endodontics/endo_prod_40.webp' },
    { id: 41, category: 'Endodontics', name: 'Chlorhexidine 2% Irrigating Solution JK', price: '45 EGP', desc: 'Usage: Root canal irrigation and disinfection during endodontic treatment, providing potent broad-spectrum antimicrobial | Quantity/Size: 1 Plastic Bottle × 250 ml | Origin: JK Dental Vision — Egypt', img: 'assets/products/endodontics/endo_prod_41.webp' },
    { id: 42, category: 'Endodontics', name: 'MANI H-Files #08 25mm', price: '230 EGP', desc: 'Usage: Manual cleaning, shaping, and efficient removal of dentin | Quantity/Size: 1 Pack × 6 Files (Size #08, 25 mm length) | Origin: MANI, INC. — Japan', img: 'assets/products/endodontics/endo_prod_42.webp' },
    { id: 43, category: 'Endodontics', name: 'MANI H-Files #10 25mm', price: '210 EGP', desc: 'Usage: Manual cleaning, enlargement, and efficient removal of dentin  | Quantity/Size: 1 Pack × 6 Files (Size #10, 25 mm length) | Origin: MANI, INC. — Japan', img: 'assets/products/endodontics/endo_prod_43.webp' },
    { id: 44, category: 'Endodontics', name: 'MANI H-Files #15 25mm', price: '180 EGP', desc: 'Usage: Manual cleaning, enlargement, and efficient removal of dentin  | Quantity/Size: 1 Pack × 6 Files (Size #15, 25 mm length) | Origin: MANI, INC. — Japan', img: 'assets/products/endodontics/endo_prod_44.webp' },
    { id: 45, category: 'Endodontics', name: 'MANI H-Files #20 25mm', price: '180 EGP', desc: 'Usage: Manual cleaning, enlargement, and efficient removal of dentin  | Quantity/Size: 1 Pack × 6 Files (Size #20, 25 mm length) | Origin: MANI, INC. — Japan', img: 'assets/products/endodontics/endo_prod_45.webp' },
    { id: 46, category: 'Endodontics', name: 'MANI H-Files #25 25mm', price: '180 EGP', desc: 'Usage: Manual cleaning, enlargement, and efficient removal of dentin  | Quantity/Size: 1 Pack × 6 Files (Size #25, 25 mm length) | Origin: MANI, INC. — Japan', img: 'assets/products/endodontics/endo_prod_46.webp' },
    { id: 47, category: 'Endodontics', name: 'MANI H-Files #30 25mm', price: '180 EGP', desc: 'Usage: Manual cleaning, enlargement, and efficient removal of dentin  | Quantity/Size: 1 Pack × 6 Files (Size #30, 25 mm length) | Origin: MANI, INC. — Japan', img: 'assets/products/endodontics/endo_prod_47.webp' },
    { id: 48, category: 'Endodontics', name: 'MANI H-Files #35 25mm', price: '180 EGP', desc: 'Usage: Manual cleaning, enlargement, and efficient removal of dentin  | Quantity/Size: 1 Pack × 6 Files (Size #35, 25 mm length) | Origin: MANI, INC. — Japan', img: 'assets/products/endodontics/endo_prod_48.webp' },
    { id: 49, category: 'Endodontics', name: 'MANI H-Files #40 25mm', price: '180 EGP', desc: 'Usage: Manual cleaning, enlargement, and efficient removal of dentin  | Quantity/Size: 1 Pack × 6 Files (Size #40, 25 mm length) | Origin: MANI, INC. — Japan', img: 'assets/products/endodontics/endo_prod_49.webp' },
    { id: 50, category: 'Endodontics', name: 'MANI H-Files #15:40 25mm', price: '180 EGP', desc: 'Usage: Manual cleaning, enlargement, and efficient removal of dentin  | Quantity/Size: 1 Pack × 6 Files (Assorted Size #15:40 , 25 mm length) | Origin: MANI, INC. — Japan', img: 'assets/products/endodontics/endo_prod_50.webp' },
    { id: 51, category: 'Endodontics', name: 'MANI H-Files #45:80 25mm', price: '210 EGP', desc: 'Usage: Manual cleaning, enlargement, and efficient removal of dentin  | Quantity/Size: 1 Pack × 6 Files (Assorted Size #45:80 , 25 mm length) | Origin: MANI, INC. — Japan', img: 'assets/products/endodontics/endo_prod_51.webp' },
    { id: 52, category: 'Endodontics', name: 'MANI  H-Files Assorted Sets (31mm)', price: '190-220 EGP', desc: 'Usage: Manual cleaning, shaping, and efficient removal of dentin  | Quantity/Size: (1 Pack × Assorted #15–40 / 1 paxk Assorted #45–80, each containing 6 files at 31 mm length) | Origin: MANI, INC. — Japan', img: 'assets/products/endodontics/endo_prod_52.webp' },
    { id: 53, category: 'Endodontics', name: 'MANI  K-Files #08 25mm', price: '220 EGP', desc: 'Usage: Manual initial canal negotiation, probing, and scouting calcified | Quantity/Size: 1 Pack × 6 Files (Size #08, 25 mm length) | Origin: MANI, INC. — Japan', img: 'assets/products/endodontics/endo_prod_53.webp' },
    { id: 54, category: 'Endodontics', name: 'MANI  K-Files #10 25mm', price: '180 EGP', desc: 'Usage: Manual initial canal negotiation, probing, and scouting calcified | Quantity/Size: 1 Pack × 6 Files (Size #10, 25 mm length) | Origin: MANI, INC. — Japan', img: 'assets/products/endodontics/endo_prod_54.webp' },
    { id: 55, category: 'Endodontics', name: 'MANI  K-Files #15 25mm', price: '175 EGP', desc: 'Usage: Manual initial canal negotiation, probing, and scouting calcified | Quantity/Size: 1 Pack × 6 Files (Size #15, 25 mm length) | Origin: MANI, INC. — Japan', img: 'assets/products/endodontics/endo_prod_55.webp' },
    { id: 56, category: 'Endodontics', name: 'MANI  K-Files #20 25mm', price: '175 EGP', desc: 'Usage: Manual initial canal negotiation, probing, and scouting calcified | Quantity/Size: 1 Pack × 6 Files (Size #20, 25 mm length) | Origin: MANI, INC. — Japan', img: 'assets/products/endodontics/endo_prod_56.webp' },
    { id: 57, category: 'Endodontics', name: 'MANI  K-Files #25 25mm', price: '175 EGP', desc: 'Usage: Manual initial canal negotiation, probing, and scouting calcified | Quantity/Size: 1 Pack × 6 Files (Size #25, 25 mm length) | Origin: MANI, INC. — Japan', img: 'assets/products/endodontics/endo_prod_57.webp' },
    { id: 58, category: 'Endodontics', name: 'MANI  K-Files #30 25mm', price: '175 EGP', desc: 'Usage: Manual initial canal negotiation, probing, and scouting calcified | Quantity/Size: 1 Pack × 6 Files (Size #30, 25 mm length) | Origin: MANI, INC. — Japan', img: 'assets/products/endodontics/endo_prod_58.webp' },
    { id: 59, category: 'Endodontics', name: 'MANI  K-Files #35 25mm', price: '175 EGP', desc: 'Usage: Manual initial canal negotiation, probing, and scouting calcified | Quantity/Size: 1 Pack × 6 Files (Size #35 , 25 mm length) | Origin: MANI, INC. — Japan', img: 'assets/products/endodontics/endo_prod_59.webp' },
    { id: 60, category: 'Endodontics', name: 'MANI  K-Files #40 25mm', price: '175 EGP', desc: 'Usage: Manual initial canal negotiation, probing, and scouting calcified | Quantity/Size: 1 Pack × 6 Files (Size #40, 25 mm length) | Origin: MANI, INC. — Japan', img: 'assets/products/endodontics/endo_prod_60.webp' },
    { id: 61, category: 'Endodontics', name: 'MANI  K-Files #15:40 25mm', price: '175 EGP', desc: 'Usage: Manual initial canal negotiation, probing, and scouting calcified | Quantity/Size: 1 Pack × 6 Files (Size #15:40 , 25 mm length) | Origin: MANI, INC. — Japan', img: 'assets/products/endodontics/endo_prod_61.webp' },
    { id: 62, category: 'Endodontics', name: 'MANI  K-Files #45:80  25mm', price: '180 EGP', desc: 'Usage: Manual initial canal negotiation, probing, and scouting calcified | Quantity/Size: 1 Pack × 6 Files (Size #45:80 , 25 mm length) | Origin: MANI, INC. — Japan', img: 'assets/products/endodontics/endo_prod_62.webp' },
    { id: 63, category: 'Endodontics', name: 'MANI  K-Files 21mm Range', price: '190 EGP', desc: 'Usage: Manual initial negotiation, scouting, pathfinding, cleaning, and shaping of short or restricted root canals | Quantity/Size: Complete 21 mm Series (Individual & Assorted Packs across sizes #06, #08, #10, #15, #20, #25, #30, #35, #40, and Assorted #15–40; 6 files per pack) | Origin: MANI, INC. — Japan', img: 'assets/products/endodontics/endo_prod_63.webp' },
    { id: 64, category: 'Endodontics', name: 'MANI  K-Files Assorted #15-40 , #45-80 31mm', price: '190 EGP', desc: 'Usage: Manual progressive cleaning, shaping, and establishing canal pathway in extra-long root canals | Quantity/Size: 1 Pack × 6 Files (Assorted Sizes #15, #20, #25, #30, #35, #40, 31 mm length) | Origin: MANI, INC. — Japan', img: 'assets/products/endodontics/endo_prod_64.webp' },
    { id: 65, category: 'Endodontics', name: 'MANI K-Files #06 25mm', price: '300 EGP', desc: 'Usage: Manual initial canal negotiation, scouting, and pathfinding for extremely narrow or tight root canals | Quantity/Size: 1 Pack × 6 Files (Size #06, 25 mm length) | Origin: MANI, INC. — Japan', img: 'assets/products/endodontics/endo_prod_65.webp' },
    { id: 66, category: 'Endodontics', name: 'Gutta Percha Points (.04 / .06 Taper)', price: '130 EGP', desc: 'Usage: Permanent obturation and complete 3D sealing of prepared root canals in combination with an endodontic sealer | Quantity/Size: 1 Box × 60 Points (Available in .04 and .06 Tapers; Sizes #20, #25, #30, #40, Assorted #15–40, and Assorted #45–80) | Origin: Meta Biomed Co., Ltd. — South Korea', img: 'assets/products/endodontics/endo_prod_66.webp' },
    { id: 67, category: 'Endodontics', name: 'Absorbent Paper Points (.04 / .06 Taper)', price: '130 EGP', desc: 'Usage: Thorough drying and fluid absorption of prepared root canals prior to obturation or intracanal medication placement | Quantity/Size: 1 Box × 60 Points (Available in .04 and .06 Tapers; Sizes #20, #25, #30, #40, Assorted #15–40, and Assorted #45–80) | Origin: Meta Biomed Co., Ltd. — South Korea', img: 'assets/products/endodontics/endo_prod_67.webp' },
    { id: 68, category: 'Endodontics', name: 'Protaper Gutta Percha Points (F1, F2, F3)', price: '200 EGP', desc: 'Usage: Permanent obturation and 3D root canal sealing designed specifically to match canals prepared with ProTaper rotary file systems (F1, F2, F3) | Quantity/Size: 1 Box × 60 Points (Length Marked; Assorted F1-F2–F3 or individual sizes F1, F2, F3) | Origin: Meta Biomed Co., Ltd. — South Korea', img: 'assets/products/endodontics/endo_prod_68.webp' },
    { id: 69, category: 'Endodontics', name: 'Standard .02 Taper Absorbent Paper Points', price: '125 EGP', desc: 'Usage: Thorough drying and fluid absorption of standard root canals prior to obturation or medication placement | Quantity/Size: 1 Box × 60 Points (Length-marked, Size #15-40 Assorted; also available in individual sizes #20, #25, #30, #40, and #45-80) | Origin: Meta Biomed Co., Ltd. — South Korea', img: 'assets/products/endodontics/endo_prod_69.webp' },
    { id: 70, category: 'Endodontics', name: 'Standard .02 Taper Gutta Percha Points', price: '125 EGP', desc: 'Usage: Permanent obturation and 3D filling of standard root canals following preparation with ISO-standard instruments | Quantity/Size: 1 Box × 60 Points (Assorted sizes #15 to #40; also available in individual sizes #20, #25, #30, #40, and #45-80) | Origin: Meta Biomed Co., Ltd. — South Korea', img: 'assets/products/endodontics/endo_prod_70.webp' },
    { id: 71, category: 'Endodontics', name: 'MANI Gates Glidden Drills (Sizes #1–#6)', price: '350 EGP', desc: 'Usage: Enlarging the coronal and middle portions of the root canal, removing bulk tooth structure, or preparing space for posts | Quantity/Size: 1 Pack × 6 Drills (Available in individual sizes #1, #2, #3, #4, #5, #6, or Assorted #1–6) | Origin: Japan – mani', img: 'assets/products/endodontics/endo_prod_71.webp' },
    { id: 72, category: 'Endodontics', name: 'MANI Spreaders 25mm', price: '220 EGP', desc: 'Usage: Lateral condensation of gutta-percha points during root canal obturation to tightly compact and seal the canal space | Quantity/Size: 1 Pack × 6 Spreaders (Assorted Sizes #15, #20, #25, #30, #35, #40, 25 mm length; also available in individual sizes #20, #25, #30) | Origin: MANI, INC. — Japan', img: 'assets/products/endodontics/endo_prod_72.webp' },
    { id: 73, category: 'Endodontics', name: 'MANI Peeso Reamers Assorted #1-6 32mm', price: '350 EGP', desc: 'Usage: Widening and flattening the coronal and middle third of the root canal or preparing post space during endodontic procedures | Quantity/Size: 1 Pack × 6 Reamers (Assorted Sizes #1 to #6, 32 mm length) | Origin: MANI, INC. — Japan', img: 'assets/products/endodontics/endo_prod_73.webp' },
    { id: 74, category: 'Endodontics', name: 'MANI Flexible K-Files Assorted #15-40 25mm', price: '230 EGP', desc: 'Usage: Manual cleaning, shaping, and negotiating curved or calcified root canals during endodontic treatment due to enhanced flexibility | Quantity/Size: 1 Pack × 6 Files (Assorted Sizes #15, #20, #25, #30, #35, #40, 25 mm length) or one size of 15-20-25-30-40 | Origin: MANI, INC. — Japan', img: 'assets/products/endodontics/endo_prod_74.webp' },
    { id: 75, category: 'Endodontics', name: 'MANI D Finders (Sizes #08, #10, #15)', price: '250 EGP', desc: 'Usage: Locating, negotiating, and penetrating calcified, narrow, or severely curved root canals due to high torsional strength and a sharp tip | Quantity/Size: 1 Pack × 6 Files (Available in sizes #08, #10, and #15; lengths 21mm or 25mm) | Origin: MANI, INC. — Japan', img: 'assets/products/endodontics/endo_prod_75.webp' },
    { id: 76, category: 'Endodontics', name: 'ROGIN Entrance Files 25mm  Path files', price: '275 EGP', desc: 'Usage: Creating initial coronal access and opening root canal orifices | Quantity/Size: L25mm, #13-19. 3pcs | Origin & Manufacturer: Made in China — Rogin Medical Co., Ltd', img: 'assets/products/endodontics/endo_prod_76.webp' },
    { id: 100, category: 'Restorative', name: '3M Filtek Z250 XT Universal', price: '1,450 EGP', desc: 'Nano-hybrid universal restorative composite with excellent polish retention.', img: 'assets/products/3m_filtek_z250.webp' },
    { id: 101, category: 'Restorative', name: 'GC Fuji I Luting Cement', price: '1,250 EGP', desc: 'Glass ionomer luting cement for crowns, bridges, and inlays.', img: 'assets/products/gc_fuji_1.jpg' },
    { id: 102, category: 'Restorative', name: 'Ivoclar Tetric N-Ceram', price: '1,100 EGP', desc: 'Universal nano-optimized composite for anterior and posterior restorations.', img: 'assets/products/ivoclar_tetric.jpg' },
    { id: 103, category: 'Restorative', name: '3M Filtek P60 Posterior', price: '1,350 EGP', desc: 'Packable composite restorative formulated for high-wear posterior loads.', img: '' },
    { id: 104, category: 'Restorative', name: 'Dentsply Prime & Bond NT', price: '1,600 EGP', desc: 'One-component dental adhesive system with nanofiller technology.', img: '' },
    { id: 110, category: 'Prosthodontics', name: 'Acrostone self cure P+L  150g  green', price: '350 EGP', desc: 'Powder + Liquid 150g Self-curing acrylic material for dental laboratory use. Made in Egypt (Stock: 2)', img: 'assets/products/prosthetics/prosthetic_prod_1.webp' },
    { id: 111, category: 'Prosthodontics', name: 'Acrostone self cure P+L  150g  colors', price: '350 EGP', desc: 'Powder + Liquid 150g Self-curing acrylic material for dental laboratory use. Made in Egypt (Stock: 2)', img: 'assets/products/prosthetics/prosthetic_prod_2.webp' },
    { id: 112, category: 'Prosthodontics', name: 'Acrostone self cure Liquid 75ml', price: '175 EGP', desc: 'Liquid 75ml Self-curing acrylic material for dental laboratory use. Made in Egypt (Stock: 1)', img: 'assets/products/prosthetics/prosthetic_prod_3.webp' },
    { id: 113, category: 'Prosthodontics', name: 'Acrostone soft liner  P+L 150g', price: '1260 EGP', desc: 'Powder + Liquid 150g Soft relining material for acrylic dentures to improve comfort. Made in Egypt (Stock: 2)', img: 'assets/products/prosthetics/prosthetic_prod_4.webp' },
    { id: 114, category: 'Prosthodontics', name: 'Glass ionomer cement china P+L', price: '150 EGP', desc: '20 g Powder + 15 ml Liquid Used for dental restorations, luting crowns, bridges, and liners. Made in China (Stock: 2)', img: 'assets/products/prosthetics/prosthetic_prod_5.webp' },
    { id: 115, category: 'Prosthodontics', name: 'GC Fuji 1 capsule', price: '145 EGP for one capsule', desc: 'Radiopaque glass ionomer luting cement for crowns, bridges, and brackets. Made in Japan Box : 50 cap. (Stock: 4)', img: 'assets/products/prosthetics/prosthetic_prod_6.webp' },
    { id: 116, category: 'Prosthodontics', name: 'GC Fuji 1 P + L', price: '3850 EGP', desc: '35 g Powder + 20 ml Liquid Radiopaque glass ionomer luting cement for crowns, bridges, and brackets. Made in Japan (Stock: 0)', img: 'assets/products/prosthetics/prosthetic_prod_7.webp' },
    { id: 117, category: 'Prosthodontics', name: 'GC Fuji-cem capsule', price: '210 EGP for one capsule', desc: 'Box : 50 cap. Self-adhesive resin luting cement for crowns, bridges, inlays, and onlays. Made in Japan (Stock: 0)', img: 'assets/products/prosthetics/prosthetic_prod_8.webp' },
    { id: 118, category: 'Prosthodontics', name: 'Medicem promedica', price: '1850 EGP', desc: 'Size: 15g Powder + 10g (approx. 8mL) Liquid. Glass ionomer luting cement for crowns, bridges, inlays, onlays, and orthodontic bands. Made in Germany (Stock: 0)', img: 'assets/products/prosthetics/prosthetic_prod_9.webp' },
    { id: 119, category: 'Prosthodontics', name: 'Provitemp automix itena', price: '1600 EGP', desc: 'Size: 1 automix syringe (5mL / approx. 8.6g) + 10 mixing tips. Non-eugenol, resin-based temporary cement for provisional crowns and bridges. Made in France. (Stock: 1)', img: 'assets/products/prosthetics/prosthetic_prod_10.webp' },
    { id: 120, category: 'Prosthodontics', name: 'Dentotemp itena', price: '1500 EGP for 1syr', desc: 'Size: 2 automix syringe (5mL / approx. 8.6g) + 20 mixing tips. Long-term temporary cement for provisional crowns, bridges, and implant-retained restorations. Made in France. (Stock: 1)', img: 'assets/products/prosthetics/prosthetic_prod_11.webp' },
    { id: 121, category: 'Prosthodontics', name: 'Totalcem itena', price: '1950 EGP', desc: 'Size: 1 automix syringe (8g) + 20 mixing tips. Self-etch and self-adhesive resin cement for permanent luting of crowns, bridges, inlays, onlays, and posts. Made in France. (Stock: 1)', img: 'assets/products/prosthetics/prosthetic_prod_12.webp' },
    { id: 122, category: 'Prosthodontics', name: 'Cavex temporary cement', price: '750 EGP', desc: 'Size: 35g Base + 16g Catalyst. Eugenol-free temporary cement for provisional crowns and bridges. Made in Netherlands . (Stock: 1)', img: 'assets/products/prosthetics/prosthetic_prod_13.webp' },
    { id: 123, category: 'Prosthodontics', name: 'Micron luting prevest', price: '550 EGP', desc: 'Size: 15g Powder + 10mL Liquid. Translucent fine particle glass ionomer luting cement for crowns, bridges, and inlays. Made in India. (Stock: 1)', img: 'assets/products/prosthetics/prosthetic_prod_14.webp' },
    { id: 124, category: 'Prosthodontics', name: 'Nova glass-L luting', price: '720 EGP', desc: 'Size: 15g Powder + 10mL Liquid. Radiopaque glass ionomer luting cement for crowns, bridges, and inlays. Made in Turkey. (Stock: 1)', img: 'assets/products/prosthetics/prosthetic_prod_15.webp' },
    { id: 125, category: 'Prosthodontics', name: 'z-prime plus Bisco', price: '440 EGP', desc: 'Size: 4ml bottle. Single-component primer used to enhance adhesion between resin cements and zirconia, alumina, or metal restorations. Made in USA. (Stock: 2)', img: 'assets/products/prosthetics/prosthetic_prod_16.webp' },
    { id: 126, category: 'Prosthodontics', name: 'Breeze self-adhesive resin cement', price: '1850 EGP', desc: 'Size: 1 automix syringe (typically 7.8g / 4mL). Self-adhesive resin cement used for permanent cementation of crowns, bridges, inlays, onlays, and posts. Made in USA. (Stock: 1)', img: 'assets/products/prosthetics/prosthetic_prod_17.webp' },
    { id: 127, category: 'Prosthodontics', name: 'Han temp crown', price: '1550 EGP', desc: 'Size: 50mL cartridge. Temporary crown and bridge material used for making provisional restorations. Made in South Korea . (Stock: 1)', img: 'assets/products/prosthetics/prosthetic_prod_18.webp' },
    { id: 128, category: 'Prosthodontics', name: 'Ultradent silane', price: '525 EGP', desc: 'Size: 1 syringe (1.2 mL / 0.96 g) + 2 delivery tips. Single-component silane coupling agent used to enhance bond strength between resin cements and porcelain/composite restorations. Made in USA . (Stock: 1)', img: 'assets/products/prosthetics/prosthetic_prod_19.webp' },
    { id: 129, category: 'Prosthodontics', name: 'Denture box citizen', price: '33 EGP', desc: 'Size: small / large. Plastic storage box with ventilation holes used for dentures, orthodontic retainers, or mouthguards. Made in China. (Stock: 66)', img: 'assets/products/prosthetics/prosthetic_prod_20.webp' },
    { id: 130, category: 'Prosthodontics', name: 'Denture box', price: '20 EGP', desc: 'Size: small / large. Plastic storage box with ventilation holes used for dentures, orthodontic retainers, or mouthguards. Made in Egypt. (Stock: 21)', img: 'assets/products/prosthetics/prosthetic_prod_21.webp' },
    { id: 131, category: 'Prosthodontics', name: 'Impression bite trays large', price: '950 EGP', desc: 'Size: 40 pcs. large Disposable plastic bite registration trays with net liners used for accurate bite impressions and check-bites. Made in China. (Stock: 0)', img: 'assets/products/prosthetics/prosthetic_prod_22.webp' },
    { id: 132, category: 'Prosthodontics', name: 'Impression bite trays small', price: '950 EGP', desc: 'Size: 50 pcs. small Disposable plastic bite registration trays with net liners used for accurate bite impressions and check-bites. Made in China. (Stock: 8)', img: 'assets/products/prosthetics/prosthetic_prod_23.webp' },
    { id: 133, category: 'Prosthodontics', name: 'Impression bite trays interior', price: '950 EGP', desc: 'Size: 20 pcs. interior Disposable plastic bite impression trays with a mesh liner designed for taking accurate bite registrations and impressions of interior arches. Made in China. (Stock: 8)', img: 'assets/products/prosthetics/prosthetic_prod_24.webp' },
    { id: 134, category: 'Prosthodontics', name: 'Veneer applicator sticks', price: '160 EGP', desc: 'Size: Box 20 pcs. Disposable placement sticks featuring sticky adhesive tips designed for secure holding, handling, and precise positioning of delicate dental veneers, inlays, or crowns. Made in China. (Stock: 3 pcs.)', img: 'assets/products/prosthetics/prosthetic_prod_25.webp' },
    { id: 135, category: 'Prosthodontics', name: 'Zhermack Hydrogum 5', price: '535 EGP', desc: 'Weight: 453 g (1 lb). Fast-setting, high-precision alginate impression material featuring 5 days of dimensional stability and a mangoustan scent. Made in Italy . (Stock: 9)', img: 'assets/products/prosthetics/prosthetic_prod_26.webp' },
    { id: 136, category: 'Prosthodontics', name: 'Alginate Cavex CA37', price: '495 EGP', desc: 'Weight: 500 g (1 lb). All-purpose, normal-setting alginate impression material used for making dental impressions with solid tear resistance and smooth surface reproduction. Made in Netherlands. (Stock: 5)', img: 'assets/products/prosthetics/prosthetic_prod_27.webp' },
    { id: 137, category: 'Prosthodontics', name: 'Zhermack Tropicalgin', price: '475 EGP', desc: 'Weight: 453 g (1 lb). Normal-setting, chromatic alginate impression material with a color-phase indicator and a lemon and tropical scent. Made in Italy. (Stock: 4)', img: 'assets/products/prosthetics/prosthetic_prod_28.webp' },
    { id: 138, category: 'Prosthodontics', name: 'Zhermack Zetalgin', price: '295 EGP', desc: 'Weight: 453 g (1 lb). Alginate impression material used for making dental impressions, featuring a mint scent. Made in Italy. (Stock: 4)', img: 'assets/products/prosthetics/prosthetic_prod_29.webp' },
    { id: 139, category: 'Prosthodontics', name: 'Zhermack Zetaplus Intro Kit L', price: '295 EGP', desc: 'Kit Contents: Zetaplus Putty (900 mL) Oranwash L Light Body (140 mL) Indurent Gel Catalyst (60 mL) Mixing Pad & Measuring Spoon C-Silicone dental impression material kit used for two-stage impression technique or single-stage technique with two viscosities. Made in Italy. (Stock: 4)', img: 'assets/products/prosthetics/prosthetic_prod_30.webp' },
    { id: 140, category: 'Prosthodontics', name: 'Zhermack Zetaplus Putty', price: '1050 EGP', desc: 'Zetaplus Putty (900 mL) High final hardness C-Silicone putty impression material used for preliminary dental impressions, featuring a mint scent Made in Italy. (Stock: 1)', img: 'assets/products/prosthetics/prosthetic_prod_31.webp' },
    { id: 141, category: 'Prosthodontics', name: 'Zhermack Oranwash L', price: '625 EGP', desc: 'Oranwash L Light Body (140 mL) Hydrocompatible, low-viscosity C-Silicone light body impression material used for second-stage dental impressions, featuring an orange scent. Made in Italy. (Stock: 1)', img: 'assets/products/prosthetics/prosthetic_prod_32.webp' },
    { id: 142, category: 'Prosthodontics', name: 'Zhermack Indurent Gel', price: '550 EGP', desc: 'Indurent Gel Catalyst (60 mL) Gel catalyst specifically designed for use with Zhermack C-Silicone dental impression materials (such as Zetaplus and Oranwash). Made in Italy. (Stock: 1)', img: 'assets/products/prosthetics/prosthetic_prod_33.webp' },
    { id: 143, category: 'Prosthodontics', name: 'Zhermack Elite HD+ Light Body', price: '1450 EGP', desc: 'Hydrophilic, low-viscosity A-Silicone (addition silicone) light body impression material with a fast-setting formula, designed for high-precision dental impressions. Volume / Kit Contents: 100 mL total (2 x 50 mL cartridges) + 12 yellow mixing tips. Made in Italy. (Stock: 1)', img: 'assets/products/prosthetics/prosthetic_prod_34.webp' },
    { id: 144, category: 'Prosthodontics', name: 'Zhermack Elite HD+ Putty Soft', price: '1850 EGP', desc: 'High-precision, addition silicone (A-Silicone) putty soft impression material featuring a fast-setting formula, ideal for two-stage or single-stage dental impression techniques. Volume / Kit Contents: 500 mL total (250 mL Base + 250 mL Catalyst) and 2 measuring spoons. Made in Italy. (Stock: 1)', img: 'assets/products/prosthetics/prosthetic_prod_35.webp' },
    { id: 145, category: 'Prosthodontics', name: 'Dentax Modelling Wax', price: '225 EGP', desc: 'Dental modelling wax sheets used in laboratories for modeling prosthetic bases, fabricating bite rims, and creating wax-ups. Type: Modelling Wax (Pink / Red). Made in Egypt . (Stock: 1)', img: 'assets/products/prosthetics/prosthetic_prod_36.webp' },
    { id: 146, category: 'Prosthodontics', name: 'Dentax Carving Wax', price: '30 EGP', desc: 'Dental carving wax blocks specifically formulated for dental students and technicians to practice tooth morphology, carving, and anatomical shaping. Type: Carving Wax (available in multiple colors: Red, Yellow, Blue). Made in Egypt . (Stock: 18)', img: 'assets/products/prosthetics/prosthetic_prod_37.webp' },
    { id: 147, category: 'Prosthodontics', name: 'Zhermack Occlufast Rock', price: '825 EGP', desc: 'Thixotropic, extra-hard A-Silicone (addition silicone) material specifically developed for high-precision bite registration with an ultra-fast setting time. Volume / Kit Contents: 100 mL total (2 x 50 mL cartridges) + 12 green mixing tips. Made in Italy. (Stock: 0.5)', img: 'assets/products/prosthetics/prosthetic_prod_38.webp' },
    { id: 148, category: 'Prosthodontics', name: 'Aluminum Impression Trays', price: '15 EGP', desc: 'dental impression trays used to hold alginate or other impression materials securely in place, featuring holes that ensure optimal mechanical retention. Material:  aluminum. Available Sizes: Size 1, Size 2, Size 3 (available as full arch pairs or partials) Made in Egypt . (Stock: 144)', img: 'assets/products/prosthetics/prosthetic_prod_39.webp' },
    { id: 149, category: 'Prosthodontics', name: 'Stainless Steel Impression Trays', price: '55 EGP', desc: 'dental impression trays designed to hold alginate and various impression materials firmly. Material: High-quality, durable stainless steel,  autoclavable for repeated sterilization. Size : 1 , 2 , 3 , particle (1/2) Made in Egypt . (Stock: 1)', img: 'assets/products/prosthetics/prosthetic_prod_40.webp' },
    { id: 150, category: 'Prosthodontics', name: 'Hiflex Tracing Sticks (green stricks)', price: '325 EGP', desc: 'Thermoplastic impression compound sticks (Green Sticks) used for border molding, extension of impression trays, and capturing accurate functional margins. Quantity: 10 sticks per box. Made by Prevest (India) (Stock: 2)', img: 'assets/products/prosthetics/prosthetic_prod_41.webp' },
    { id: 151, category: 'Prosthodontics', name: 'Dental Rubber Mixing Bowls', price: '20 EGP', desc: 'Flexible bowls used for manual mixing of alginates, plaster, and stone. Made in Egypt. (Stock: 8)', img: 'assets/products/prosthetics/prosthetic_prod_42.webp' },
    { id: 152, category: 'Prosthodontics', name: 'Dental Cement Spatula', price: '45 EGP', desc: 'Double-ended stainless steel spatula used for manual mixing of dental cements and liners. Made in Pakistan. (Stock: 6)', img: 'assets/products/prosthetics/prosthetic_prod_43.webp' },
    { id: 153, category: 'Prosthodontics', name: 'Dental Syringe metal', price: '225 EGP', desc: 'Surgical-grade stainless steel aspirating syringe used for administering local anesthesia cartridges. Made in Pakistan. (Stock: 1)', img: 'assets/products/prosthetics/prosthetic_prod_44.webp' },
    { id: 154, category: 'Prosthodontics', name: 'Dental Wax Carver', price: '45 EGP', desc: 'Double-ended stainless steel instrument used for carving, shaping, and modeling dental wax designs and patterns. Made in Pakistan. (Stock: 6)', img: 'assets/products/prosthetics/prosthetic_prod_45.webp' },
    { id: 155, category: 'Prosthodontics', name: 'Dental Plaster Knife / Wax Knife', price: '40 EGP', desc: 'Double-ended instrument with a wooden handle, used in dental laboratories for cutting, scraping, and trimming plaster models or wax. Made in Pakistan. (Stock: 5)', img: 'assets/products/prosthetics/prosthetic_prod_46.webp' },
    { id: 156, category: 'Prosthodontics', name: 'Gingival Retraction Cord Applicator', price: '65 EGP', desc: 'Double-ended stainless steel instrument designed for placing and packing retraction cords into the sulcus. Made in Pakistan. (Stock: 2)', img: 'assets/products/prosthetics/prosthetic_prod_47.webp' },
    { id: 157, category: 'Prosthodontics', name: 'Gingival Retraction Cord (Z-Twist Type)', price: '125 EGP', desc: 'Gingival retraction cord impregnated with epinephrine, used for temporary tissue displacement and fluid control before taking dental impressions. Available Sizes: 000, 00, 0, 1, 2. Made in China. (Stock: 2)', img: 'assets/products/prosthetics/prosthetic_prod_48.webp' },
    { id: 158, category: 'Prosthodontics', name: 'AtriaPak Gingival Retraction Cord', price: '250 EGP', desc: 'Knitted, non-medicated gingival retraction cord used for temporary gingival tissue displacement and sulcus expansion before impressions. Length: 254 cm (100 inches) per bottle. Available Sizes: 000, 00, 0, 1, 2,3. Made by Atriamed (Stock: 1)', img: 'assets/products/prosthetics/prosthetic_prod_49.webp' },
    { id: 159, category: 'Prosthodontics', name: 'VOCO Retraction Paste', price: '220 EGP', desc: 'Astringent retraction paste used for effective temporary widening and drying of the gingival sulcus before impression taking. Contains aluminum chloride to ensure highly efficient hemostasis and fluid control. Made by VOCO (Germany) (Stock: 80)', img: 'assets/products/prosthetics/prosthetic_prod_50.webp' },
    { id: 160, category: 'Prosthodontics', name: 'Denston Hard Dental Stone', price: '125 EGP', desc: 'hard dental stone featuring high compressive strength and low expansion, used for pouring master models, crowns, and bridge frameworks. Weight: 1 Kg. Made by Atay Yapı (Turkey) (Stock: 2)', img: 'assets/products/prosthetics/prosthetic_prod_51.webp' },
    { id: 161, category: 'Prosthodontics', name: 'Denston Extra Hard Dental Stone', price: '125 EGP', desc: 'extra hard  stone featuring maximum fracture resistance and high precision, ideal for fabricating dies, implant models, and complex prosthodontic work. Weight: 1 Kg. Made by Atay Yapı (Turkey) (Stock: 1)', img: 'assets/products/prosthetics/prosthetic_prod_52.webp' },
    { id: 162, category: 'Prosthodontics', name: 'Surgical Blades', price: '290 EGP', desc: 'Sterile, single-use carbon steel blades used for precise surgical incisions and soft tissue cutting. Packaging: 100 Pcs per box (individually foil-wrapped and sterilized by GAMMA radiation). Available Sizes: 11, 15, 15c. Made in china. (Stock: 3)', img: 'assets/products/prosthetics/prosthetic_prod_53.webp' },
    { id: 163, category: 'Prosthodontics', name: 'Stainless Steel Kidney Dish (Kidney Tray)', price: '25 EGP', desc: 'Stainless steel kidney tray used in dental clinics and medical facilities for holding soiled dressings, discarded materials, or small instruments during procedures. Designed with a kidney-shaped profile to fit easily against the patient\'s body to catch any fluids or debris. Made in Egypt. (Stock: 1)', img: 'assets/products/prosthetics/prosthetic_prod_54.webp' },
    { id: 164, category: 'Prosthodontics', name: 'Dental Edentulous Cast (Gypsum Model)', price: '20 EGP', desc: 'Pre-cast dental plaster model representing an edentulous (toothless) arch, used in dental laboratories and universities for educational purposes, training, and fabricating complete dentures. Made in Egypt. (Stock: 24)', img: 'assets/products/prosthetics/prosthetic_prod_55.webp' },
    { id: 165, category: 'Prosthodontics', name: 'Dental Dentulous Cast (Gypsum Study Model)', price: '30 EGP', desc: 'Pre-cast dental plaster model representing a fully dentulous (with teeth) upper and lower arch in occlusion, used in dental laboratories and universities for study, orthodontic analysis, and student training. Made in Egypt. (Stock: 2)', img: 'assets/products/prosthetics/prosthetic_prod_56.webp' },
    { id: 166, category: 'Prosthodontics', name: 'El-Banna Dental  Model', price: '225 EGP', desc: 'Used by students for preclinical training (cavity preparation & cutting). Features removable acrylic teeth and a pink base. Made in Egypt. (Stock: 1)', img: 'assets/products/prosthetics/prosthetic_prod_57.webp' },
    { id: 167, category: 'Prosthodontics', name: 'Citizen Plastic Impression Trays', price: '220 EGP', desc: 'plastic trays used for holding impression material to take accurate oral molds. Disposable ( autoclavable ) and designed for single-use to ensure optimal hygiene. Made in China. Dental Rubber Base Dispensing Gun : (Stock: 4)', img: 'assets/products/prosthetics/prosthetic_prod_58.webp' },
    { id: 168, category: 'Prosthodontics', name: 'Dental Rubber Base Dispensing Gun (1:1 / 2:1)', price: '350 EGP', desc: 'Used for dispensing rubber base, silicones, and other dual-cartridge impression materials. Ensures effortless, even extrusion with a comfortable manual grip Made in China. (Stock: 1)', img: 'assets/products/prosthetics/prosthetic_prod_59.webp' },
    { id: 169, category: 'Prosthodontics', name: 'Plastic Alginate Mixing Spatulas', price: '10 EGP', desc: 'Used for hand-mixing dental impression materials (like alginate) and plaster in rubber bowls. Made of flexible, durable plastic that is easy to clean. Made in Egypt . (Stock: 9)', img: 'assets/products/prosthetics/prosthetic_prod_60.webp' },
    { id: 170, category: 'Prosthodontics', name: 'Aomai Dental Butane Torch small', price: '175 EGP', desc: 'Refillable gas torch used in dental laboratories for heating wax, carvers, and dental instruments. Features an adjustable jet flame, lock switch, and a stable base. Brand: Aomai. (Stock: 2)', img: 'assets/products/prosthetics/prosthetic_prod_61.webp' },
    { id: 171, category: 'Prosthodontics', name: 'Aomai Dental Butane Torch large', price: '270 EGP', desc: 'Refillable gas torch used in dental laboratories for heating wax, carvers, and dental instruments. Features an adjustable jet flame, lock switch, and a stable base. Brand: Aomai. (Stock: 2)', img: 'assets/products/prosthetics/prosthetic_prod_62.webp' },
    { id: 172, category: 'Prosthodontics', name: 'Butane Gas Refill Canister (غاز تعبئة الولاعات)', price: '65 EGP', desc: 'Used for refilling butane torches, lighters, and various dental lab burners. Contains highly purified butane gas to ensure a clean, consistent flame. Made in Egypt (Stock: 3)', img: 'assets/products/prosthetics/prosthetic_prod_63.webp' },
    { id: 200, category: 'Instruments', name: 'Dental Gingival Retraction Cord Applicator', price: '65 EGP', desc: 'Usage: Gently placing and packing gingival retraction cord into the sulcus around a prepared tooth to displace tissue and ensure accurate impressions | Quantity/Size: 1 Single Instrument (Double-ended) | Origin & Manufacturer: Pakistan', img: 'assets/products/instruments/inst_prod_1.webp' },
    { id: 201, category: 'Instruments', name: 'Dental Composite Applicator', price: '45 EGP', desc: 'Usage: Placing, condensing, and contouring composite resin materials | Quantity/Size: 1 Single Instrument (Double-ended) | Origin & Manufacturer: Pakistan', img: 'assets/products/instruments/inst_prod_2.webp' },
    { id: 202, category: 'Instruments', name: 'Dental Instrument Cleaning Brush Set', price: '25 EGP', desc: 'Usage: Scrubbing, cleaning, and removing stubborn debris | Quantity/Size: 1 Set × 3 Brushes | Origin & Manufacturer: China', img: 'assets/products/instruments/inst_prod_3.webp' },
    { id: 203, category: 'Instruments', name: 'Dental Ball Burnisher', price: '45 EGP', desc: 'Usage: Smoothing, contouring, and polishing amalgam or composite restorations, as well as blending restorative materials against cavity margins | Quantity/Size: 1 Single Instrument (Double-ended) | Origin & Manufacturer: Pakistan', img: 'assets/products/instruments/inst_prod_4.webp' },
    { id: 204, category: 'Instruments', name: 'Dental Conical Burnisher', price: '45 EGP', desc: 'Usage: Smoothing, shaping, and finishing restorative materials (such as amalgam or composite) as well as contouring occlusal anatomies | Quantity/Size: 1 Single Instrument (Double-ended) | Origin & Manufacturer: Pakistan (Standard dental surgical grade instrument)', img: 'assets/products/instruments/inst_prod_5.webp' },
    { id: 205, category: 'Instruments', name: 'Dental Curved Surgical Scissors', price: '55 EGP', desc: 'Usage: Making precise curved cuts in soft tissue, trimming gum margins, or cutting sutures and fine dressing materials during surgical procedures | Quantity/Size: 1 Single Instrument | Origin & Manufacturer: Pakistan', img: 'assets/products/instruments/inst_prod_6.webp' },
    { id: 206, category: 'Instruments', name: 'Disposable Dental Instrument Kit', price: '10 EGP', desc: 'Usage: Single-use examination and clinical procedures | Quantity/Size: 1 Single-use sterilized pack containing (mirror-twezzer-prob) | Origin & Manufacturer: Egypt', img: 'assets/products/instruments/inst_prod_7.webp' },
    { id: 207, category: 'Instruments', name: 'Dental Contrast Background', price: '125 EGP', desc: 'Usage: Placed behind the teeth during intraoral photography to provide a dark, non-reflective background | Quantity/Size: by pcs | Origin & Manufacturer: Egypt', img: 'assets/products/instruments/inst_prod_8.webp' },
    { id: 208, category: 'Instruments', name: 'Dental Orthodontic Photography Mirrors Kit', price: '375 EGP', desc: 'Usage: Intraoral reflection and clinical photography to capture clear, high-contrast images | Quantity/Size:  Set of 3pcs. assorted double-sided or single-sided mirrors in various shapes | Origin & Manufacturer: Egypt', img: 'assets/products/instruments/inst_prod_9.webp' },
    { id: 209, category: 'Instruments', name: 'Dental Mosquito', price: '75 EGP', desc: 'Usage: Clamping small blood vessels to control bleeding, or holding small delicate items, fragments, and sutures during oral surgery | Quantity/Size: 1 Single Instrument | Origin & Manufacturer: pakistan', img: 'assets/products/instruments/inst_prod_10.webp' },
    { id: 210, category: 'Instruments', name: 'Dental Surgical Scissors', price: '55 EGP', desc: 'Usage: Cutting and trimming gingival tissue, cutting suture threads, | Quantity/Size: 1 Single Instrument | Origin & Manufacturer: Pakistan', img: 'assets/products/instruments/inst_prod_11.webp' },
    { id: 211, category: 'Instruments', name: 'Dental Excavator', price: '45 EGP', desc: 'Usage: Removing soft carious dentin, temporary filling materials, and debris from tooth cavity preparations | Quantity/Size: 1 Single Instrument | Origin & Manufacturer: pakistan', img: 'assets/products/instruments/inst_prod_12.webp' },
    { id: 212, category: 'Instruments', name: 'Adult Dental Forceps Kit', price: '2250 EGP', desc: 'Usage: Gripping, loosening, and extracting adult teeth from their sockets during oral surgery and routine extractions | Quantity/Size: 1 Complete Kit (Includes an assortment of forceps | Origin & Manufacturer:  pakistan', img: 'assets/products/instruments/inst_prod_13.webp' },
    { id: 213, category: 'Instruments', name: 'Pediatric Dental Forceps Kit', price: '2150 EGP', desc: 'Usage: Gripping, loosening, and extracting primary (deciduous) teeth from their sockets during pediatric dental procedures and pediatric oral surgery | Quantity/Size: 1 Complete Kit (Includes a specialized assortment of forceps | Origin & Manufacturer: pakistan', img: 'assets/products/instruments/inst_prod_14.webp' },
    { id: 214, category: 'Instruments', name: 'Dental Surgical Elevator Kit', price: '885 EGP', desc: 'Usage: Luxating teeth, severing periodontal ligaments, and elevating teeth or roots smoothly from their sockets prior to extraction | Quantity/Size: 1 Complete Kit (Includes  assortment of elevators featuring  straight, apexo, and cryer) | Origin & Manufacturer: pakistan', img: 'assets/products/instruments/inst_prod_15.webp' },
    { id: 215, category: 'Instruments', name: 'Dental Crossbar Elevator (T-Bar)', price: '280 EGP', desc: 'Usage: Providing maximum leverage and torque for the extraction of stubborn roots, impacted teeth, and fractured root fragments during oral surgery | Quantity/Size: 1 Single instrument | Origin & Manufacturer:  Pakistan', img: 'assets/products/instruments/inst_prod_16.webp' },
    { id: 216, category: 'Instruments', name: 'Dental Cryer Elevator Right / left', price: '220 EGP', desc: 'Usage: Elevating and extracting root fragments, molars, and impacted teeth from their sockets by applying leverage against the alveolar bone | Quantity/Size: 1 Single Instrument cryer | Origin & Manufacturer:  pakistan', img: 'assets/products/instruments/inst_prod_17.webp' },
    { id: 217, category: 'Instruments', name: 'Dental Curved Elevator Right /left', price: '220 EGP', desc: 'Usage: Luxating, loosening, and lifting root tips or impacted teeth from their sockets with precise rotational leverage | Quantity/Size: 1 Single Instrument curved | Origin & Manufacturer: Pakistan', img: 'assets/products/instruments/inst_prod_18.webp' },
    { id: 218, category: 'Instruments', name: 'Dental Straight Elevator', price: '110 EGP', desc: 'Usage: Luxating teeth, severing periodontal ligaments, and elevating teeth or root fragments straight out of their sockets during extractions | Quantity/Size: 1 Single Instrument straight stainless steel | Origin & Manufacturer: Pakistan', img: 'assets/products/instruments/inst_prod_19.webp' },
    { id: 219, category: 'Instruments', name: 'Dental Calcium Hydroxide Applicator', price: '45 EGP', desc: 'Usage: Picking up, carrying, and placing calcium hydroxide | Quantity/Size: 1 Single Instrument | Origin & Manufacturer: Pakistan', img: 'assets/products/instruments/inst_prod_20.webp' },
    { id: 220, category: 'Instruments', name: 'Dental Carver', price: '45 EGP', desc: 'Usage: Carving, shaping, and contouring freshly placed amalgam or composite restorative materials to restore natural tooth anatomy and margins | Quantity/Size: 1 Single Instrument | Origin & Manufacturer: Pakistan', img: 'assets/products/instruments/inst_prod_21.webp' },
    { id: 221, category: 'Instruments', name: 'Dental plastic Instrument', price: '45 EGP', desc: 'Usage: Transporting, placing, packing, and contouring aesthetic composite resin restorative materials into cavity preparations | Quantity/Size: 1 Single Instrument | Origin & Manufacturer: Pakistan', img: 'assets/products/instruments/inst_prod_22.webp' },
    { id: 222, category: 'Instruments', name: 'Condenser', price: '45 EGP', desc: 'Usage: Packing, condensing, and pressing freshly placed restorative materials | Quantity/Size: 1 Single Instrument | Origin & Manufacturer: Pakistan', img: 'assets/products/instruments/inst_prod_23.webp' },
    { id: 223, category: 'Instruments', name: 'Tooth-Shaped Patient Hand Mirror', price: '80 EGP', desc: 'Usage: Allows patients to view their oral hygiene progress | Quantity/Size: 1 Single Handheld Mirror | Origin & Manufacturer: Eg', img: 'assets/products/instruments/inst_prod_24.webp' },
    { id: 224, category: 'Instruments', name: 'Dental Mouth Mirror Handle', price: '25 EGP', desc: 'Usage: Holding and maneuvering intraoral mouth mirror heads | Quantity/Size: 1 Single Instrument | Origin & Manufacturer: Pakistan', img: 'assets/products/instruments/inst_prod_25.webp' },
    { id: 225, category: 'Instruments', name: 'Dental Mouth Mirror Head', price: '12 EGP', desc: 'Usage: Providing indirect vision, light reflection | Quantity/Size: by pcs | Origin & Manufacturer: Pakistan', img: 'assets/products/instruments/inst_prod_26.webp' },
    { id: 226, category: 'Instruments', name: 'MEGA FS Front Surface Mirrors', price: '95 EGP', desc: 'Usage: Providing a sharply focused, high-clarity front-surface reflected image | Quantity/Size: 1 pcs | Origin & Manufacturer: Germany / Hahnenkratt', img: 'assets/products/instruments/inst_prod_27.webp' },
    { id: 227, category: 'Instruments', name: 'Dental Rubber Dam Forceps', price: '300 EGP', desc: 'Usage: Opening, positioning, and locking rubber dam clamps | Quantity/Size: 1 Single Instrument | Origin & Manufacturer: Pakistan', img: 'assets/products/instruments/inst_prod_28.webp' },
    { id: 228, category: 'Instruments', name: 'Rubber Dam Frame U-Shaped', price: '55 EGP', desc: 'Usage: Holding and supporting the rubber dam sheet taut and away from the patient\'s face | Quantity/Size: 1 Single Instrument | Origin & Manufacturer: Pakistan', img: 'assets/products/instruments/inst_prod_29.webp' },
    { id: 229, category: 'Instruments', name: 'Dental Plastic Foldable', price: '100 EGP', desc: 'Usage: Supporting and stretching the rubber dam sheet taut away from the oral cavity | Quantity/Size: 1 Single Frame | Origin & Manufacturer: China', img: 'assets/products/instruments/inst_prod_30.webp' },
    { id: 230, category: 'Instruments', name: 'Dental Rubber Dam Punch', price: '425 EGP', desc: 'Usage: Punching clean, precise holes of varying sizes into a rubber dam sheet to accommodate specific teeth during isolation | Quantity/Size: 1 Single Instrument | Origin & Manufacturer: Pakistan', img: 'assets/products/instruments/inst_prod_31.webp' },
    { id: 231, category: 'Instruments', name: 'Dental Mixing Impression Material Gun', price: '350 EGP', desc: 'Usage: Dispensing, mixing, and applying dual-component dental impression materials | Quantity/Size: 1 Single Dispensing Gun | Origin & Manufacturer: China', img: 'assets/products/instruments/inst_prod_32.webp' },
    { id: 232, category: 'Instruments', name: 'Dental Composite Dispenser Gun', price: '200 EGP', desc: 'Usage: Loading, holding, and precisely dispensing composite resin or luting material directly into cavity preparations from compule/carpule tips | Quantity/Size: 1 Single Dispensing Gun | Origin & Manufacturer: China', img: 'assets/products/instruments/inst_prod_33.webp' },
    { id: 233, category: 'Instruments', name: 'Dental  Capsule Gun (Applicator Gun)', price: '950 EGP', desc: 'Usage: Dispensing and applying mixed dental amalgam or glass ionomer capsules directly into cavity preparations | Quantity/Size: 1 Single Instrument | Origin & Manufacturer: USA', img: 'assets/products/instruments/inst_prod_34.webp' },
    { id: 234, category: 'Instruments', name: 'Plastic Autoclavable Dental Impression Trays', price: '220 EGP', desc: 'Usage: Containing and supporting dental impression materials  | Quantity/Size: Set of multiple assorted sizes | Origin & Manufacturer: China - Citizen', img: 'assets/products/instruments/inst_prod_35.webp' },
    { id: 235, category: 'Instruments', name: 'Dental Patient Napkin Holder', price: '20 EGP', desc: 'Usage: Securing and holding patient dental bibs or napkins in place around the neck during dental examinations and procedures | Quantity/Size: 1 Single Piece | Origin & Manufacturer: Egypt', img: 'assets/products/instruments/inst_prod_36.webp' },
    { id: 236, category: 'Instruments', name: 'Aluminum Impression Trays', price: '15 EGP', desc: 'Usage: Holding and carrying impression materials into the oral cavity | Quantity/Size: By pcs (Available individually in multiple sizes  (1,2,3,1/2) | Origin & Manufacturer: Egypt', img: 'assets/products/instruments/inst_prod_37.webp' },
    { id: 237, category: 'Instruments', name: 'Autoclavable Dental Patient Napkin Holder', price: '125 EGP', desc: 'Usage: Securing and holding patient dental bibs or napkins in place around the neck during dental examinations and procedures | Quantity/Size: 1 Single Piece | Origin & Manufacturer: China', img: 'assets/products/instruments/inst_prod_38.webp' },
    { id: 238, category: 'Instruments', name: 'Dental Orthodontic Tweezers', price: '125 EGP', desc: 'Usage: Picking up, positioning, and placing orthodontic brackets accurately onto the tooth surface during bonding procedures | Quantity/Size: 1 Single Instrument | Origin & Manufacturer: Pakistan', img: 'assets/products/instruments/inst_prod_39.webp' },
    { id: 239, category: 'Instruments', name: 'Dental Cotton Roll Holder', price: '65 EGP', desc: 'Usage: Securing and holding cotton rolls firmly against the buccal mucosa to isolate the surgical site and absorb saliva during dental procedures | Quantity/Size:  by pcs | Origin & Manufacturer: China', img: 'assets/products/instruments/inst_prod_40.webp' },
    { id: 240, category: 'Instruments', name: 'Dental Probe', price: '45 EGP', desc: 'Usage: Examining tooth surfaces for caries, detecting dental calculus, exploring pockets, and checking restoration margins | Quantity/Size: 1 Single Instrument | Origin & Manufacturer:  Pakistan', img: 'assets/products/instruments/inst_prod_41.webp' },
    { id: 241, category: 'Instruments', name: 'Dental Cheek Retractor (C-Shape)', price: '30 EGP', desc: 'Usage: Retracting the lips and cheeks gently to provide maximum visibility | Quantity/Size: By pcs | Origin & Manufacturer: Eg', img: 'assets/products/instruments/inst_prod_42.webp' },
    { id: 242, category: 'Instruments', name: 'Dental Cheek Retractor', price: '30 EGP', desc: 'Usage: Retracting lips and cheeks to provide clear visibility and maximum access to the oral cavity | Quantity/Size: By pcs | Origin & Manufacturer: china -citizen', img: 'assets/products/instruments/inst_prod_43.webp' },
    { id: 243, category: 'Instruments', name: 'Dental Silicone Lip and Cheek Retractor (Mouth Opener)', price: '200 EGP', desc: 'Usage: Retracting lips and cheeks to provide comfortable, wide-open access and high visibility to the oral cavity | Quantity/Size: By pcs | Origin & Manufacturer: Eg', img: 'assets/products/instruments/inst_prod_44.webp' },
    { id: 244, category: 'Instruments', name: 'Dental Rubber Dam holder', price: '125 EGP', desc: 'Usage: Placing, expanding, and positioning rubber dam clamps securely onto teeth | Quantity/Size: 1 pcs | Origin & Manufacturer: China', img: 'assets/products/instruments/inst_prod_45.webp' },
    { id: 245, category: 'Instruments', name: 'Matrix Band (Tofflemire )', price: '120 EGP', desc: 'Usage: Securing, holding, and tightening matrix bands around a prepared tooth | Quantity/Size: 1 Single Instrument | Origin & Manufacturer: China', img: 'assets/products/instruments/inst_prod_46.webp' },
    { id: 246, category: 'Instruments', name: 'Dental Silicone Mixing Bowl', price: '20 EGP', desc: 'Usage: Mixing dental materials such as impression materials (alginate, plaster) | Quantity/Size: By pcs  | Origin & Manufacturer: China', img: 'assets/products/instruments/inst_prod_47.webp' },
    { id: 247, category: 'Instruments', name: 'Dental Scaler', price: '45 EGP', desc: 'Usage: Removing supragingival dental plaque, calculus, and stains from tooth surfaces during scaling | Quantity/Size: 1 Single Instrument | Origin & Manufacturer: pakistan', img: 'assets/products/instruments/inst_prod_48.webp' },
    { id: 248, category: 'Instruments', name: 'Dental Periodontal Probe', price: '45 EGP', desc: 'Usage: Measuring periodontal pocket depths, assessing gingival bleeding | Quantity/Size: 1 Single Instrument | Origin & Manufacturer: Pakistan', img: 'assets/products/instruments/inst_prod_49.webp' },
    { id: 249, category: 'Instruments', name: 'Dental Cement Spatula', price: '45 EGP', desc: 'Usage: Mixing dental cements, bases, and liners on a glass slab or mixing pad | Quantity/Size: 1 Single Instrument | Origin & Manufacturer: Pakistan', img: 'assets/products/instruments/inst_prod_50.webp' },
    { id: 250, category: 'Instruments', name: 'Dental Carpule Syringe', price: '225 EGP', desc: 'Usage: Holding and injecting local anesthetic carpules/cartridges | Quantity/Size: 1 Single Instrument | Origin & Manufacturer: Pakistan', img: 'assets/products/instruments/inst_prod_51.webp' },
    { id: 251, category: 'Instruments', name: 'Dental Wax Carver', price: '45 EGP', desc: 'Usage: Carving, shaping, and contouring dental wax patterns | Quantity/Size: 1 Single Instrument | Origin & Manufacturer: Pakistan', img: 'assets/products/instruments/inst_prod_52.webp' },
    { id: 252, category: 'Instruments', name: 'Dental Wax Knife', price: '40 EGP', desc: 'Usage: Cutting, trimming, and shaping dental wax blocks , and plaster models in the dental laboratory | Quantity/Size: 1 Single Instrument | Origin & Manufacturer: Pakistan', img: 'assets/products/instruments/inst_prod_53.webp' },
    { id: 253, category: 'Instruments', name: 'Dental Scalpel Handle', price: '45 EGP', desc: 'Usage: Holding surgical scalpel blades | Quantity/Size: 1 Single Instrument | Origin & Manufacturer: Pakistan', img: 'assets/products/instruments/inst_prod_54.webp' },
    { id: 254, category: 'Instruments', name: 'Stainless Steel Kidney Dish', price: '25 EGP', desc: 'Usage: Holding surgical instruments, soiled cotton rolls, dressings, or collecting waste and fluids during clinical procedures | Quantity/Size: 1 Single Basin | Origin & Manufacturer: Eg', img: 'assets/products/instruments/inst_prod_55.webp' },
    { id: 255, category: 'Instruments', name: 'Dental Plastic Spatula', price: '10 EGP', desc: 'Usage: Mixing dental materials such as alginate, plaster, and cements | Quantity/Size: By pcs | Origin & Manufacturer: China', img: 'assets/products/instruments/inst_prod_56.webp' },
    { id: 256, category: 'Instruments', name: 'Dental Cotton Roll Dispenser', price: '250 EGP', desc: 'Usage: Storing and dispensing sterile cotton rolls hygienically, one at a time | Quantity/Size: 1 Single Dispenser Unit | Origin & Manufacturer: China', img: 'assets/products/instruments/inst_prod_57.webp' },
    { id: 257, category: 'Instruments', name: 'Dental Needle Holder', price: '45 EGP', desc: 'Usage: Gripping, holding, and guiding surgical suture needles | Quantity/Size: 1 Single Instrument | Origin & Manufacturer: Pakistan', img: 'assets/products/instruments/inst_prod_58.webp' },
    { id: 258, category: 'Instruments', name: 'Dental Needle Holder 18 cm', price: '110 EGP', desc: 'Usage: Gripping, holding, and guiding surgical suture needles | Quantity/Size: pcs. 18 cm | Origin & Manufacturer: Pakistan', img: 'assets/products/instruments/inst_prod_59.webp' },
    { id: 259, category: 'Instruments', name: 'Dental Surgical Scalpel Blades (Size 11 & 15)', price: '295 EGP', desc: 'Usage: Making precise surgical incisions | Quantity/Size: 100 pcs per box ; Size 11 / 15 | Origin & Manufacturer: China', img: 'assets/products/instruments/inst_prod_60.webp' },
    { id: 260, category: 'Instruments', name: 'Dental Surgical Blade (Size 15C)', price: '485 EGP', desc: 'Usage: Making precise, short, and curved incisions | Quantity/Size: 100 pcs per box ; size 15c | Origin & Manufacturer: China', img: 'assets/products/instruments/inst_prod_61.webp' },
    { id: 261, category: 'Instruments', name: 'Dental Rubber Dam Clamps', price: '45 EGP', desc: 'Usage: Securing rubber dam sheets around individual teeth to isolate the operating field, maintain a dry environment | Quantity/Size: By pcs | Origin & Manufacturer: Pakistan', img: 'assets/products/instruments/inst_prod_62.webp' },
    { id: 262, category: 'Instruments', name: 'Dental Tweezers W lock', price: '60 EGP', desc: 'Usage: Handling, transferring, and placing small items  | Quantity/Size: 1 Single Instrument | Origin & Manufacturer: Pakistan', img: 'assets/products/instruments/inst_prod_63.webp' },
    { id: 263, category: 'Instruments', name: 'Dental Tweezers', price: '50 EGP', desc: 'Usage: Handling, transferring, and placing small items | Quantity/Size: 1 Single Instrument | Origin & Manufacturer: Pakistan', img: 'assets/products/instruments/inst_prod_64.webp' },
    { id: 264, category: 'Instruments', name: 'Dental  Mortar and Pestle', price: '35 EGP', desc: 'Usage: Grinding, mixing, and pulverizing dental powders, ceramic materials, porcelain, and filling components in the dental laboratory | Quantity/Size: 1 Set | Origin & Manufacturer: China', img: 'assets/products/instruments/inst_prod_65.webp' },
    { id: 265, category: 'Instruments', name: 'Dental Glass Dappen Dish', price: '15 EGP', desc: 'Usage: Holding and mixing small amounts of dental liquids, monomer, acrylic, bonding agents, etching gels, or sealants  | Quantity/Size: By pcs  | Origin & Manufacturer:  China', img: 'assets/products/instruments/inst_prod_66.webp' },
    { id: 266, category: 'Instruments', name: 'Dental Bite Block (Mouth Prop )', price: '35 EGP', desc: 'Usage: Keeping the patient\'s mouth comfortably open | Quantity/Size: By pcs (Single pieces available in Small, Medium, and Large sizes, autoclavable silicone design) | Origin & Manufacturer: China', img: 'assets/products/instruments/inst_prod_67.webp' },
    { id: 267, category: 'Instruments', name: 'Dental Minnesota Retractor', price: '35 EGP', desc: 'Usage: Retracting the cheeks, lips, and tongue away from the surgical or operating site | Quantity/Size: By pcs | Origin & Manufacturer: Pakistan', img: 'assets/products/instruments/inst_prod_68.webp' },
    { id: 268, category: 'Instruments', name: 'Periosteal Elevator', price: '45 EGP', desc: 'Usage: Reflecting, elevating, and retracting mucoperiosteal tissue away from bone during oral surgery and periodontal procedures | Quantity/Size: 1 Single Instrument | Origin & Manufacturer: Pakistan', img: 'assets/products/instruments/inst_prod_69.webp' },
    { id: 269, category: 'Instruments', name: 'Dental Amalgam Carrier', price: '55 EGP', desc: 'Usage: Picking up, carrying, and dispensing freshly mixed dental amalgam filling material directly into prepared tooth cavities | Quantity/Size: 1 Single Instrument | Origin & Manufacturer: Pakistan', img: 'assets/products/instruments/inst_prod_70.webp' },
    { id: 300, category: 'Implantology', name: 'Osstem GS III Surgical Kit', price: '22,000 EGP', desc: 'Comprehensive surgical kit for precision dental implant placement.', img: 'dental_implant_kit_1779981511316.webp' },
    { id: 301, category: 'Implantology', name: 'Dentium SuperLine Implant', price: '3,500 EGP', desc: 'SLA surface internal hex titanium dental implant fixture.', img: '' },
    { id: 302, category: 'Implantology', name: 'Implant Motor Woodpecker', price: '45,000 EGP', desc: 'Brushless surgical implant motor with 20:1 contra-angle handpiece.', img: '' },
    { id: 310, category: 'Orthodontics', name: 'Metal Brackets MBT 022', price: '1,800 EGP', desc: 'Precision 3M style stainless steel orthodontic brackets.', img: '' },
    { id: 311, category: 'Orthodontics', name: 'Niti Archwires 016 Upper', price: '850 EGP', desc: 'Super elastic thermal NiTi orthodontic alignment archwires.', img: '' },
    { id: 312, category: 'Orthodontics', name: 'Ligature Ties (40 Sticks)', price: '250 EGP', desc: 'High-elasticity orthodontic elastomeric ligature ties.', img: '' },
    { id: 320, category: 'Equipment', name: 'Woodpecker UDS-A LED Scaler', price: '8,200 EGP', desc: 'Piezo ultrasonic scaler with independent auto-water supply bottle.', img: 'dental_ultrasonic_scaler_1779981671477.webp' },
    { id: 321, category: 'Equipment', name: 'NSK Ti-Max Z95L Handpiece', price: '12,500 EGP', desc: 'Titanium 1:5 increasing high-speed contra-angle air turbine.', img: 'assets/products/nsk_handpiece.jpg' },
    { id: 322, category: 'Equipment', name: 'Dental Autoclave 23L Class B', price: '75,000 EGP', desc: 'Large capacity vacuum steam sterilizer with digital diagnostic display.', img: '' },
    { id: 330, category: 'Periodontics', name: 'Gracey Curettes Set #1/2-#13/14', price: '4,500 EGP', desc: 'Surgical grade stainless steel area-specific periodontal curettes.', img: '' },
    { id: 331, category: 'Periodontics', name: 'Ultrasonic Perio Tips', price: '1,200 EGP', desc: 'Subgingival deep pocket cleaning ultrasonic scaler tips.', img: '' },
    { id: 340, category: 'Laboratory', name: 'Zirconia Blocks (High Translucent)', price: '2,400 EGP', desc: 'Premium multi-layer blocks for dental CAD/CAM milling.', img: '' },
    { id: 341, category: 'Laboratory', name: 'Dental Porcelain Furnace', price: '120,000 EGP', desc: 'Precision vacuum firing furnace for all dental ceramic restorations.', img: '' },
    { id: 350, category: 'Sterilization', name: 'Sterilization Pouches (200pcs)', price: '380 EGP', desc: 'Self-seal sterilization pouches with steam and EO color indicators.', img: '' },
    { id: 351, category: 'Sterilization', name: 'Enzymatic Detergent 5L', price: '1,100 EGP', desc: 'Multi-enzyme instrument pre-soak and cleaning solution.', img: '' },
];

function renderProducts(filter = 'all', searchQuery = '') {
    const grid = document.querySelector('.product-grid');
    if (!grid) return;

    grid.innerHTML = '';
    let filtered = filter === 'all' ? productData : productData.filter(p => p.category === filter);

    if (searchQuery) {
        const query = searchQuery.toLowerCase();
        filtered = filtered.filter(p =>
            p.name.toLowerCase().includes(query) ||
            p.category.toLowerCase().includes(query) ||
            p.desc.toLowerCase().includes(query)
        );
    }

    if (filtered.length === 0) {
        grid.innerHTML = '<div class="no-results">No products found for this selection.</div>';
        return;
    }

    filtered.forEach(p => {
        const card = document.createElement('div');
        card.className = 'product-card animate-in';
        card.innerHTML = `
            <div class="prod-img">
                ${p.img ? `<img src="${p.img}" alt="${p.name}" loading="lazy">` : `<div class="placeholder-icon"><i class="fas fa-boxes-stacked"></i></div>`}
            </div>
            <div class="prod-info">
                <span class="tag">${p.category}</span>
                <h3>${p.name}</h3>
                <p class="description">${p.desc}</p>
                <p class="price">${p.price}</p>
                <button class="add-to-cart" onclick="addToCart(${p.id})">Add to Cart</button>
            </div>
        `;
        grid.appendChild(card);
    });
}

function addToCart(id) {
    const product = productData.find(p => p.id === id);
    if (product) {
        alert(`Added ${product.name} to cart!`);
    }
}

document.addEventListener('DOMContentLoaded', () => {
    renderProducts();

    // Category Filter Buttons (on page)
    const filterBtns = document.querySelectorAll('.filter-btn');
    filterBtns.forEach(btn => {
        btn.addEventListener('click', () => {
            filterBtns.forEach(b => b.classList.remove('active'));
            btn.classList.add('active');
            renderProducts(btn.dataset.category);
        });
    });

    // Sub-menu/Hamburger Category Links
    const categoryLinks = document.querySelectorAll('.cat-link');
    categoryLinks.forEach(link => {
        link.addEventListener('click', (e) => {
            e.preventDefault();
            const cat = link.dataset.category;
            
            // Sync filter bar buttons if matching button exists
            filterBtns.forEach(b => {
                if (b.dataset.category === cat) {
                    filterBtns.forEach(btn => btn.classList.remove('active'));
                    b.classList.add('active');
                }
            });
            
            renderProducts(cat);
            // Scroll to products
            const prodSection = document.getElementById('products');
            if (prodSection) {
                prodSection.scrollIntoView({ behavior: 'smooth' });
            }
            // Close mobile menu if open
            const navLinks = document.querySelector('.nav-links');
            const mobileCats = document.querySelector('.mobile-nav-categories');
            if (navLinks && navLinks.classList.contains('active')) {
                navLinks.classList.remove('active');
            }
            if (mobileCats && mobileCats.classList.contains('active')) {
                mobileCats.classList.remove('active');
            }
        });
    });

    // Mobile Menu Toggle
    const menuToggle = document.querySelector('.menu-toggle');
    const navLinks = document.querySelector('.nav-links');
    const mobileCats = document.querySelector('.mobile-nav-categories');

    if (menuToggle) {
        menuToggle.addEventListener('click', () => {
            navLinks.classList.toggle('active');
            mobileCats.classList.toggle('active');
        });
    }
});
